"""added columns to user

Revision ID: 17c0b1f2fe16
Revises: 80b6127b663c
Create Date: 2021-10-23 11:54:54.730817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c0b1f2fe16'
down_revision = '80b6127b663c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('profilePath', sa.String(length=400), nullable=True))
    op.add_column('User', sa.Column('videoPath', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'videoPath')
    op.drop_column('User', 'profilePath')
    # ### end Alembic commands ###
