"""migration 0


Revision ID: 4603ae3e1547
Revises: 
Create Date: 2021-11-17 18:40:02.143205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4603ae3e1547'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appliedJobs')
    op.drop_table('dummy')
    op.drop_constraint('applicant_user_id_fkey', 'applicant', type_='foreignkey')
    op.create_foreign_key(None, 'applicant', 'auth', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('employer_user_id_fkey', 'employer', type_='foreignkey')
    op.create_foreign_key(None, 'employer', 'auth', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employer', type_='foreignkey')
    op.create_foreign_key('employer_user_id_fkey', 'employer', 'auth', ['user_id'], ['id'])
    op.drop_constraint(None, 'applicant', type_='foreignkey')
    op.create_foreign_key('applicant_user_id_fkey', 'applicant', 'auth', ['user_id'], ['id'])
    op.create_table('dummy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='dummy_pkey')
    )
    op.create_table('appliedJobs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"appliedJobs_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('jobID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('userID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['jobID'], ['jobs.id'], name='appliedJobs_jobID_fkey'),
    sa.ForeignKeyConstraint(['userID'], ['auth.id'], name='appliedJobs_userID_fkey'),
    sa.PrimaryKeyConstraint('id', name='appliedJobs_pkey')
    )
    # ### end Alembic commands ###
