"""Initial migration.

Revision ID: e08cbe8273c9
Revises: 
Create Date: 2021-10-09 12:27:59.389959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e08cbe8273c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dummydb')
    op.alter_column('dummy', 'date_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('dummy_name_key', 'dummy', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('dummy_name_key', 'dummy', ['name'])
    op.alter_column('dummy', 'date_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_table('dummydb',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dummydb_pkey'),
    sa.UniqueConstraint('name', name='dummydb_name_key')
    )
    # ### end Alembic commands ###
